import { writeFileSync } from "node:fs";

import { log } from "./log.js";

const message = "hello world again";

writeFileSync("./test.txt", "this is test data generated by index.ts");

log(message);
